### ISSUE TITLE
ImportError: No module named 'musikernel'

### ISSUE THREAD

**Issue by quesada** [j3ffhubb/musikernel#24]
After doing make clean; make; make install:

`/musikernel-master/src/pydaw $ python3 musikernel2.py&
[1] 16497
quesada@acer ~/Seafile/musikernel-master/src/pydaw $ sys.argv == ['musikernel2.py']
/home/quesada/Seafile/musikernel-master/src/lib/musikernel2/pydaw/python
Traceback (most recent call last):
  File "musikernel2.py", line 42, in <module>
    import musikernel
ImportError: No module named 'musikernel'`

locate musickernel.py returns nothing.
All dependencies installed on Solus 64.
Any idea what could be wrong?

Thanks

**Comment by j3ffhubb** [comment]
It should be `locate musikernel2.py`.  If that doesn't work, post the output of `make install`.  Also try `which musikernel2.py`, and run that version.

**Comment by quesada** [comment]
`~/Seafile/musikernel-master/src/pydaw $ ./musikernel2.py
sys.argv == ['./musikernel2.py']
/home/quesada/Seafile/musikernel-master/src/lib/musikernel2/pydaw/python
Traceback (most recent call last):
  File "./musikernel2.py", line 42, in <module>
    import musikernel
ImportError: No module named 'musikernel'
quesada@acer ~/Seafile/musikernel-master/src/pydaw $ cd ..
quesada@acer ~/Seafile/musikernel-master/src $ ls
debian          install_deb.sh     minor-version.txt  tag.sh
deb.py          loc.sh             pydaw              ubuntu_deps.sh
fedora_deps.sh  major-version.txt  README_ARM.txt
gdb-fix.sh      Makefile           sbsms
quesada@acer ~/Seafile/musikernel-master/src $ sudo make install 
Password: 
install -d /usr/lib/musikernel2
install -d /usr/lib/musikernel2/sbsms
install -d /usr/lib/musikernel2/sbsms/bin
make -C pydaw PREFIX=/usr DESTDIR= install
make[1]: Entering directory '/home/quesada/Seafile/musikernel-master/src/pydaw'
rm -rf python/*.pyc python/libpydaw/*.pyc python/*~ \
python/libpydaw/*~ python/core python/*/__pycache__ \
python/mkplugins/__pycache__
install -d /usr/bin
install -m 755 musikernel2.py /usr/bin
install -d /usr/lib/musikernel2
install -d /usr/lib/musikernel2/pydaw
install -m 755 musikernel2-engine-dbg /usr/bin
install -s -m 4755 musikernel2-engine /usr/bin
install -s -m 755 musikernel2-engine \
/usr/bin/musikernel2-engine-no-root
cp -r python /usr/lib/musikernel2/pydaw
install -d /usr/lib/musikernel2/pydaw/mkengine
install -m 555 musikernel2.dll \
	/usr/lib/musikernel2/pydaw/mkengine || \
install -m 555 musikernel2.so \
	/usr/lib/musikernel2/pydaw/mkengine
install: cannot stat ‘musikernel2.dll’: No such file or directory
cp -r themes /usr/lib/musikernel2
cp -r presets /usr/lib/musikernel2
cp -r share /usr
#locale/Makefile.py /usr
install -m 644 ../major-version.txt \
	/usr/lib/musikernel2
install -m 644 ../minor-version.txt \
	/usr/lib/musikernel2
#Add the Git revision to the version.txt file if possible
make[1]: Leaving directory '/home/quesada/Seafile/musikernel-master/src/pydaw'
install sbsms/cli/sbsms /usr/lib/musikernel2/sbsms/bin
`

**Comment by quesada** [comment]
musikernel2.py is not the problem, I'm running it from /src. Is the musikernel lib that it doesn't find.

**Comment by j3ffhubb** [comment]
I'm a little unclear on what you're doing, so I'll go over the possible ways to run it that should work (pretty much anything not in this list is unlikely to work).

Use cases:
1.  Not editing the Musikernel source code, just using it:
After running `make && make install`, it's now installed to your system, and should run it from the desktop shortcut, or by running `musikernel2.py` from the terminal, which should point to `/usr/bin/musikernel2.py`.  You shouldn't run it from scripts in the Git repository if this use-case applies to you.

2.  Editing the Musikernel source code, and wanting to run it without installing to the system:
After running `make` to build the vendored dependencies, run `cd pydaw/python`, then run `./musikernel.py`.  The `musikernel2.py` script in the parent directory doesn't work unless it's installed to a standard system `PREFIX=/usr` location, it doesn't work when run from the Git repo.

I'm about 90% certain that one of those 2 will fix your problem, if not let me know.

**Comment by quesada** [comment]
On the previous comment, I did:
`quesada@acer ~/Seafile/musikernel-master $ which musikernel2.py 
/usr/bin/musikernel2.py
quesada@acer ~/Seafile/musikernel-master $ /usr/bin/musikernel2.py
sys.argv == ['/usr/bin/musikernel2.py']
/usr/lib/musikernel2/pydaw/python
Traceback (most recent call last):
  File "/usr/bin/musikernel2.py", line 42, in <module>
    import musikernel
ImportError: No module named 'musikernel'
`
now I'm sure I'm running the musikernel2.py that is on the system, not the one on musikernel-master/src/pydaw.
1 - Desktop shortcut doesn't do anything. But if I understand what you say, then I shouldn't be running musikernel-master/src/pydaw  anyway.

2 - is PREFIX=/usr the default? I see it at the top of the makefile, but it has ?= instead of =. I don't know make's syntax. In any case, I ran the default makefile as sudo make install. I run the version in /python, and I'm getting:
`./musikernel.py &
[1] 23086
quesada@acer ~/Seafile/musikernel-master/src/pydaw/python $ ICON_PATH = '/usr/share/pixmaps/musikernel2.png'



install prefix:  /usr



BIN_PATH == None
Using stylesheet /usr/lib/musikernel2/themes/default/default.pytheme
Traceback (most recent call last):
  File "./musikernel.py", line 20, in <module>
    from libpydaw import pydaw_util, pydaw_widgets, pydaw_device_dialog
  File "/home/quesada/Seafile/musikernel-master/src/pydaw/python/libpydaw/pydaw_util.py", line 1117, in <module>
    STYLESHEET = pydaw_read_file_text(STYLESHEET_FILE)
  File "/home/quesada/Seafile/musikernel-master/src/pydaw/python/libpydaw/pydaw_util.py", line 532, in pydaw_read_file_text
    with open(pi_path(a_file)) as f_handle:
PermissionError: [Errno 13] Permission denied: '/usr/lib/musikernel2/themes/default/default.pytheme'

`
No window shows up.

It's all owned by root:
` cd /usr/lib/musikernel2/themes/
 root  ⋯  lib  musikernel2  themes  ls -la
total 12
drwx------ 3 root root 4096 Nov 27 21:30 .
drwxr-xr-x 6 root root 4096 Nov 28 06:32 ..
drwx------ 2 root root 4096 Nov 27 21:30 default
 root  ⋯  lib  musikernel2  themes  cd ..
 root  /  usr  lib  musikernel2  ls -la
total 120
drwxr-xr-x   6 root root  4096 Nov 28 06:32 .
drwxr-xr-x 201 root root 90112 Nov 27 21:30 ..
-rw-r--r--   1 root root    12 Nov 28 06:32 major-version.txt
-rw-r--r--   1 root root     8 Nov 28 06:32 minor-version.txt
drwx------   2 root root  4096 Nov 27 21:30 presets
drwxr-xr-x   4 root root  4096 Nov 27 21:30 pydaw
drwxr-xr-x   3 root root  4096 Nov 27 21:30 sbsms
drwx------   3 root root  4096 Nov 27 21:30 themes
`
Phew! I feel like we are making progress.

**Comment by quesada** [comment]
BTW, Jeff, I've follow your evolution from back on the pydaw times at KVR. We exchanged plenty of ideas there. I think what you are doing is really important for linux, and I'm happy you are still pushing the project even with the opposition you had from the 'stablishment'. Best of luck!

**Comment by j3ffhubb** [comment]
Thanks for the kind words :-)

It looks like from your `ls -la` that it has `600` file permissions?  (you can run `stat /usr/lib/musikernel2/themes/default/default.pytheme` to see the octal permission).  What are the permissions on the same file in Git?  In the Git repository it should be `0664/-rw-rw-r--`.  Assuming this is something the system is doing, you could work around it by creating a root-less install, something like:

```
# do this as your user, no sudo and no root
cd [musikernel dir]/src
mkdir LOCAL
make DESTDIR=$(pwd)/LOCAL install
cd LOCAL/usr/bin
./musikernel2.py
```

Also, if you'd like to install to the /usr/local prefix, you can do:

```
cd [musikernel dir]/src
make PREFIX=/usr/local install
```

**Comment by quesada** [comment]
Finally! got to see the window rendered.

It didn't find my m-audio usb midi keyboard (it's there: ardour sees it, but I had to change to alsa-sequencer for it to see it).

Just poking around, I got mk2 to make noises, but soon it went poof:

`
signal 1 caught, trying to clean up and exit

[1]+  Aborted                 (core dumped) ./musikernel2.py
`

Argh. If stability is not there, all is lost.

**Comment by quesada** [comment]
Thanks so much for taking the time to make it work though!

**Comment by j3ffhubb** [comment]
If more files have bad permissions, it could easily crash from not being able read them.  Maybe try it in Fedora or Ubuntu?
